version: "3"

services:
  server:
    hostname: kirillzhosul-shop
    restart: always
    env_file:
      - .server.env
    volumes:
      - ./:/srv/www/kirillzhosul/shop
    ports:
      - "${COMPOSE_EXPOSED_PORT}:80"
    build: .
